name: Android Lint and Checkstyle

on: pull_request

jobs:
  lint_and_checkstyle:
    name: Lint and Checkstyle Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android/RunUsAndroid
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Run Android Linter
      run: ./gradlew lintDebug
